name: "Webpacker compile"
description: "Webpacker compile with cache"
author: "aki77"
inputs:
  cacheKeyPrefix:
    description: "Cache key prefix"
    default: "webpacker-compile"
runs:
  using: "node12"
  main: "dist/index.js"
