name: "Webpacker compile"
description: "Webpacker compile with cache"
author: "aki77"
inputs:
  cacheKeyPrefix:
    description: "Cache key prefix"
    default: "webpacker-compile"
  compileCommand:
    description: "Webpacker compile command"
    default: "bin/rake webpacker:compile"
  cachePaths:
    description: "Cache paths"
    default: |
      public/packs
      public/packs-test
      tmp/cache/webpacker
outputs:
  cache-hit:
    description: "A boolean value to indicate an exact match was found for the primary key"
runs:
  using: "node12"
  main: "dist/index.js"
